import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import BackgroundImage from '@/components/BackgroundImage';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`text-color-text font-medium bg-color-background ${inter.className}`}
      >
        <Navbar />
        {/* <BackgroundImage /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
